# Generated by Django 4.2.2 on 2023-06-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitipedia_app', '0003_fruitmodel_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitmodel',
            name='profile',
        ),
    ]
